// flow-typed signature: e00b5bd8444e533c577a104378661ab2
// flow-typed version: <<STUB>>/atom.storage_v^0.5.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom.storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom.storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom.storage/dist/atom.storage.cjs' {
  declare module.exports: any;
}

declare module 'atom.storage/dist/atom.storage.es' {
  declare module.exports: any;
}

declare module 'atom.storage/dist/atom.storage' {
  declare module.exports: any;
}

declare module 'atom.storage/dist/atom.storage.min' {
  declare module.exports: any;
}

declare module 'atom.storage/rollup.config' {
  declare module.exports: any;
}

declare module 'atom.storage/src/atom.storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom.storage/dist/atom.storage.cjs.js' {
  declare module.exports: $Exports<'atom.storage/dist/atom.storage.cjs'>;
}
declare module 'atom.storage/dist/atom.storage.es.js' {
  declare module.exports: $Exports<'atom.storage/dist/atom.storage.es'>;
}
declare module 'atom.storage/dist/atom.storage.js' {
  declare module.exports: $Exports<'atom.storage/dist/atom.storage'>;
}
declare module 'atom.storage/dist/atom.storage.min.js' {
  declare module.exports: $Exports<'atom.storage/dist/atom.storage.min'>;
}
declare module 'atom.storage/rollup.config.js' {
  declare module.exports: $Exports<'atom.storage/rollup.config'>;
}
declare module 'atom.storage/src/atom.storage.js' {
  declare module.exports: $Exports<'atom.storage/src/atom.storage'>;
}
