// flow-typed signature: 50a9750cb6d51f96d20a8e3c3460dc9e
// flow-typed version: <<STUB>>/karet_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karet/dist/karet.cjs' {
  declare module.exports: any;
}

declare module 'karet/dist/karet.es' {
  declare module.exports: any;
}

declare module 'karet/dist/karet' {
  declare module.exports: any;
}

declare module 'karet/dist/karet.min' {
  declare module.exports: any;
}

declare module 'karet/rollup.config' {
  declare module.exports: any;
}

declare module 'karet/src/karet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karet/dist/karet.cjs.js' {
  declare module.exports: $Exports<'karet/dist/karet.cjs'>;
}
declare module 'karet/dist/karet.es.js' {
  declare module.exports: $Exports<'karet/dist/karet.es'>;
}
declare module 'karet/dist/karet.js' {
  declare module.exports: $Exports<'karet/dist/karet'>;
}
declare module 'karet/dist/karet.min.js' {
  declare module.exports: $Exports<'karet/dist/karet.min'>;
}
declare module 'karet/rollup.config.js' {
  declare module.exports: $Exports<'karet/rollup.config'>;
}
declare module 'karet/src/karet.js' {
  declare module.exports: $Exports<'karet/src/karet'>;
}
